App.tsx, android/app/src/main/AndroidManifest.xml, index.share.js, ios/Podfile, ios/Podfile.lock, ios/share-extension/Base.lproj/MainInterface.storyboard, ios/share-extension/Info.plist, ios/share-extension/ShareViewController.swift, ios/share-extension/share-extension-Bridging-Header.h, ios/share-extension/share-extension.entitlements, ios/ygt.xcodeproj/project.pbxproj, ios/ygt.xcodeproj/xcshareddata/xcschemes/ygt.xcscheme, ios/ygt.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, ios/ygt/AppDelegate.mm, ios/ygt/Info.plist, ios/ygt/ygt.entitlements, package.json, src/components/Share.tsx, src/screens/Share.tsx, yarn.lock
>⚡️ `issue/7` (#12) 머지 후 머지해주세요!!!
@SenseCodeValue 님이 작업해주신 #12 를 기준으로 안드로이드도 테스트했습니다~!
실수로 #12 를 기준으로 작업을 해버려서... 추후 #12 가 머지되지 않는다면 체리픽으로 처리해야될 것 같아요.
Related issue #8 (Closed #8)
동작 영상:
https://user-images.githubusercontent.com/6638675/162627358-e8121e8f-d6ff-468f-845b-a341d23b662a.mp4
혹시 작동이 안되는 경우,
```
yarn react-native link
```
처리 후 다시 시도해보세요!
- https://github.com/meedan/react-native-share-menu
=> 공유 - react-native-share-menu 안드로이드 테스트

.github/CODEOWNERS, App.tsx, android/app/src/main/java/com/ygt/MainApplication.java, android/settings.gradle, ios/Podfile, ios/Podfile.lock, ios/ygt.xcodeproj/project.pbxproj, ios/ygt.xcodeproj/xcshareddata/xcschemes/ygt.xcscheme, ios/ygt.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, package.json, yarn.lock
- ios 환경에서 테스트 완료. 안드로이드 환경은 확인 필요합니다.
- 테스트 version: iphone 13, iOS15.5
- https://github.com/react-native-webview/react-native-webview
=> webview 추가 및 safe area 설정

src/screens/HomeScreen.tsx
안드로이드에서 dom storage 접근을 위해 
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#domstorageenabled
위 옵션을 활성화했어요.
> 물론 확인해보지 못해, 필요가 없을 수도 ...!
> 수요일 이후에 안드로이드 스튜디오 설치 후 확인해보도록 할게요 !
=> 안드로이드 dom storage 활성화

ios/ygt/LaunchScreen.storyboard, src/screens/SplashScreen.tsx, src/styles/theme.ts
[design: splash design 변경 및 launch screen 색상 수정](https://github.com/depromeet/11th_7team_app/commit/8f750b54d3ee952938213cc21455c6e48b4b7c64)
=> splash design 변경 및 launch screen 색상 수정

app.json
=> iOS app name 수정

src/screens/SplashScreen.tsx
splash icon을 감싸는 wrapper에 padding 적용
=> splash icon 사이즈 수정

android/app/src/main/res/values/strings.xml
=> 안드로이드 앱 이름 변경 (label)

android/app/build.gradle
- 안드로이드의 버전 코드를 수정합니다. 기존에는 1이여서 마켓에 올라가지 못했습니다.
=> 안드로이드의 버전 코드 수정

app.json, ios/ygt/Info.plist
=> 권한 설명 길게 설정

android/app/src/main/java/com/ygt/MainActivity.java, android/app/src/main/res/values/styles.xml, src/screens/HomeScreen.tsx
- 안드로이드 status bar 안보이는 이슈를 드디어 수정했어요!
- 삽질 양에 비해 간단한 이슈였습니다. StatusBar가 hidden={true} 이라서 생긴 것 같더라고요. (기본 값은 false인데 왜 true로 되어 있는지는 잘 모르겠습니다)
- 다만 당황스럽게도 안드로이드 웹뷰에서 safe area 적용이 안됩니다... ㅠㅠㅠ 요거 찾아보고 대응해줘야 할 것 같아요. (하단 스크린샷 첨부합니다)
Closed #64
https://reactnative.dev/docs/statusbar#hidden
=> 안드로이드 status bar 안보이는 이슈 수정

README.md
[혜성님이 작성해주신 readme](https://github.com/depromeet/ygtang-client#readme)를 app에도 추가합니다!
=> docs: readme 추가

src/screens/HomeScreen.tsx
=> iOS 제스처 옵션 추가

ios/ygt.xcodeproj/project.pbxproj, ios/ygt/Info.plist, package.json
- IOS 버전이 업데이트 되었습니다.
- package 버전도 동일하게 업데이트 합니다.
=> IOS 버전 및 package 버전 업

android/app/build.gradle
- 안드로이드의 퍼블리시를 위한 버전과 버전 코드를 올립니다. (v1.0.1, 3)
=> 안드로이드 버전 업

App.tsx, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, src/components/Share.tsx, src/components/ShareHandler.tsx, src/screens/HomeScreen.tsx
- Share 컴포넌트를 베이스로 ShareHandler를 만들었어요.
- 범용적으로 사용하는 것을 고려해 작성했기에 추후 iOS도 리팩토링해볼게요.
- 앱 딥링크를 제거했어요
- 안드로이드에서 브라우저에서 열리는 이슈를 해결했어요.
Closed #16
=> 안드로이드 공유 핸들링

src/components/YgtStatusBar.tsx, src/screens/HomeScreen.tsx
safe area원복 합니다. 대신 이번에는 하단 safe-area는 해제합니다.
=> safe area 원복 및 하단 safe area 제거

android/app/build.gradle, src/components/Share.tsx, src/components/ShareHandler.tsx
=> share의 webToken 저장 관련 로직이 빠져있던 문제 해결

README.md
[`미리 보기`](https://github.com/depromeet/ygtang-app/tree/docs/update-readme)
클라이언트 리드미와 동일하게 업데이트하면서
앱 레포에 맞는 뱃지로 업데이트했슴다
=> 리드미 이미지, 소개글, 뱃지 업데이트

ios/ygt.xcodeproj/project.pbxproj, package.json, yarn.lock
security 해결을 위해 react-native의 버전을 올려봅니다.
```diff
- "react-native": "0.68.0",
+ "react-native": "0.68.2",
```
=> react-native bump up to 0.68.2

ios/Podfile.lock, yarn.lock
=> Improper Neutralization of Special Elements used in a Command in Shell-quote

src/components/ShareHandler.tsx, src/constants/common.ts, src/hooks/useWebViewNavigateWrapping.ts
- 원래는 웹뷰단에서 message를 통해 처리하려고 했지만, 웹뷰에서 처리하기 조금 애매하더라고요.
- 이전 커밋 #94 에서 작업했던 주소 처리를 기준으로 `/add/`가 아닌 경우 창을 닫도록 작업했습니다.
=> 안드로이드에서 공유 기능 나갈 시 Share 컴포넌트 해제 처리하기

android/app/build.gradle
=> chore: 안드로이드 1.1.1 버전 업

src/constants/common.ts
실수로 작업 내용을 그대로 커밋했습니다... 그나마 다행인 점은 그동안 웹 배포가 없었다는 점이겠네요 ㅠㅠ
안드로이드 버전도 그 버전으로 그대로 올라가서 client 작업 내용 머지되면 `1.1.1-android.1`로 배포토록 하겠습니다. 혼선을 드려 죄송합니다...!
=> BASE_URI 상수 핫픽스 

android/app/build.gradle
- 핫픽스에 관련된 픽스 버전 업입니다.
- 스토어 이미지 변경도 진행토록 하겠습니다
=> 안드로이드 버전 업 (1.1.1-android.1)

android/app/build.gradle
=> chore: 안드로이드 버전 업 (v1.2.0, 14)

README.md
=> readme owner에 해성님 추가

android/app/build.gradle, android/build.gradle, package.json, yarn.lock
- 1.2.1로 버전 업합니다.
- 빌드 문제를 해결합니다.
=> 안드로이드 빌드 이슈 해결 및 버전 업

android/app/build.gradle
- 안드로이드 배포를 위해 versionCode를 상승합니다.
- 프로덕션을 배포를 위함입니다.
=> chore: 안드로이드 버전 코드 업

package.json, src/constants/common.ts
- URI를 업데이트했습니다!....
x
x
closed #131
=> fix: 모바일 공유하기 네트워크 오류

android/app/build.gradle, package.json
- 안드로이드 버전을 올립니다.
- package.json 버전을 맞춥니다!
- @sensecodevalue 제가 대윤님 작업을 이해 못하고 1.2.0으로 픽스해버렸네요... 다시 대윤님의 의견으로 반영하였습니다!!
=> 안드로이드 버전 배포 대응 v1.2.2

ios/ShareExtention/Info.plist, ios/ygt.xcodeproj/project.pbxproj, ios/ygt/Info.plist, src/components/Share.tsx, src/components/ShareHandler.tsx, src/screens/HomeScreen.tsx
- JSON.parse를 할 수 없는 경우 error를 반환하며, sentry에 계속 축적될것으로 보입니다.
- 간단하게 try-catch를 이용해서 해결했습니다.
closed #140
=> webview postMessage JSON.parse에러 해결

android/app/build.gradle, package.json
- andriod 버전과 package 버전은 1.2.3으로 변경합니다.
=> chore: version을 1.2.3 변경

android/app/build.gradle, ios/ygt.xcodeproj/project.pbxproj, package.json, src/components/WebView.tsx, src/constants/common.ts
- 버전을 1.2.4로 올립니다. (versionCode 20) (iOS는 플랫폼 이슈로... 못했습니다 ㅠㅠ)
- lint-staged가 정상 작동하지 않는 문제를 해결합니다.
- package.json 버전과 uri을 웹뷰 헤더에 실어 보냅니다. (추후 앱에서 디버깅 페이지를 만들 때 사용할 예정입니다)
=> 버전 업 (1.2.4)

README.md
수상 텍스트를 추가하고 죽어있던 LGTM 뱃지를 제거해용
=> 리드미에 수상내역 추가 및 비활성 뱃지 제거
